name: Deploy and Run App on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and Run App on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu
            rm -rf shopping
            git clone https://github.com/Rajabboy8900/shopping.git
            cd shopping

            # .env faylni yaratish
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> .env
            echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
            echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> .env
            echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env

            # Paketlarni o‘rnatish va build
            npm install
            npm run build

            # PM2 bilan ishga tushirish
            pm2 delete shopping || true
            pm2 start dist/main.js --name shopping
            pm2 save












