name: Deploy and Run App on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and Run App on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu
            rm -rf cyber-market
            git clone https://github.com/Rajabboy8900/shopping
            cd cyber-market

            # .env faylni yaratish
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
            echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
            echo "UPLOADCARE_PUBLIC_KEY=${{ secrets.UPLOADCARE_PUBLIC_KEY }}" >> .env

            # Paketlarni o'rnatish va build qilish
            npm install
            npm run build

            # Prisma migration (agar Prisma ishlatilgan bo‘lsa)
            npx prisma generate || true
            npx prisma migrate deploy || true

            # PM2 bilan ishga tushirish
            pm2 delete cyber-market || true
            pm2 start dist/main.js --name cyber-market
            pm2 save


# ///////